//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.interkassa.views;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.AttributeSet;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import com.interkassa.Interkassa_;
import com.interkassa.interact.R.id;
import com.interkassa.interact.R.layout;
import com.interkassa.models.PaymentInfo;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class PaymentsMethodChooserLayout_
    extends PaymentsMethodChooserLayout
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    public PaymentsMethodChooserLayout_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static PaymentsMethodChooserLayout build(Context context, AttributeSet attrs) {
        PaymentsMethodChooserLayout_ instance = new PaymentsMethodChooserLayout_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.payment_chooser_layout, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        interkassa = Interkassa_.getInstance_(getContext());
        getMethods();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        currencies = ((LinearLayout) hasViews.findViewById(id.currencies));
        payInfo = ((LinearLayout) hasViews.findViewById(id.pay_info));
        systems = ((LinearLayout) hasViews.findViewById(id.systems));
        progressBar = ((ProgressBar) hasViews.findViewById(id.progress));
    }

    @Override
    public void showSystems() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PaymentsMethodChooserLayout_.super.showSystems();
            }

        }
        );
    }

    @Override
    public void showPaymentInfo(final PaymentInfo t) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PaymentsMethodChooserLayout_.super.showPaymentInfo(t);
            }

        }
        );
    }

}
